name: Noticias de Barcelona

on:
  workflow_dispatch:

jobs:
  scraper-job:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: 1. Descargando el código del repositorio
      uses: actions/checkout@v4

    - name: 2. Configurando Python en el servidor
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Instalando librerías
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: 4. Generando noticias de Barcelona
      run: python barcelona_noticias.py

    - name: 5. Guardando resultado en el repositorio
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add noticias_barcelona.md
        git diff --cached --quiet || git commit -m "bot: actualizar noticias_barcelona.md [$(date +'%d/%m/%Y %H:%M')]"
        git push
